export const GET_ALL_ALPHABET_REQUEST = "GET_ALL_ALPHABET_REQUEST";
export const GET_ALL_ALPHABET_SUCCESS = "GET_ALL_ALPHABET_SUCCESS";
export const GET_ALL_ALPHABET_ERROR = "GET_ALL_ALPHABET_ERROR";

export const GET_ALPHABET_DETAILS_REQUEST = "GET_ALPHABET_DETAILS_REQUEST";
export const GET_ALPHABET_DETAILS_SUCCESS = "GET_ALPHABET_DETAILS_SUCCESS";
export const GET_ALPHABET_DETAILS_ERROR = "GET_ALPHABET_DETAILS_ERROR";

// export const GET_COMMENTS_SUCCESS = "GET_COMMENTS_SUCCESS"
// export const GET_COMMENTS_REQUEST = "GET_COMMENTS_REQUEST"
// export const GET_COMMENTS_ERROR = "GET_COMMENTS_ERROR"

// export const POST_COMMENT_SUCCESS = "POST_COMMENT_SUCCESS"
// export const POST_COMMENT_REQUEST = "POST_COMMENT_REQUEST"
// export const POST_COMMENT_ERROR = "POST_COMMENT_ERROR"
