export const GET_ALL_COURSES_REQUEST = "GET_ALL_COURSES_REQUEST";
export const GET_ALL_COURSES_SUCCESS = "GET_ALL_COURSES_SUCCESS";
export const GET_ALL_COURSES_ERROR = "GET_ALL_COURSES_ERROR";

export const ADD_WORD="ADD_WORD"
export const ADD_COURSE_REQUEST = "ADD_COURSE_REQUEST";
export const ADD_COURSE_SUCCESS = "ADD_COURSE_SUCCESS";
export const ADD_COURSE_ERROR = "ADD_COURSE_ERROR";
export const CREATE_NEW_COURSE= "CREATE_NEW_COURSE"

export const SHOW_MODAL_ADD_COURSE="SHOW_MODAL_ADD_COURSE"

export const GET_COURSE_REQUEST= "GET_COURSE_REQUEST"
export const GET_COURSE_SUCCESS= "GET_COURSE_SUCCESS"
export const GET_COURSE_ERROR= "GET_COURSE_ERROR"

export const DELETE_COURSE_REQUEST="DELETE_COURSE_REQUEST"
export const DELETE_COURSE_SUCCESS="DELETE_COURSE_SUCCESS"
export const DELETE_COURSE_ERROR="DELETE_COURSE_ERROR"

export const RESET_COURSE_MODAL="RESET_COURSE_MODAL"
