export const GET_LIST_FRIENDS_REQUEST = "GET_LIST_FRIENDS_REQUEST"
export const GET_LIST_FRIENDS_SUCCESS = "GET_LIST_FRIENDS_SUCCESS"
export const GET_LIST_FRIENDS_ERROR = "GET_LIST_FRIENDS_ERROR"

export const SEARCH_FRIENDS_REQUEST="SEARCH_FRIENDS_REQUEST"
export const SEARCH_FRIENDS_SUCCESS="SEARCH_FRIENDS_SUCCESS"
export const SEARCH_FRIENDS_ERROR="SEARCH_FRIENDS_ERROR"

export const GET_LIST_USERS_REQUEST = "GET_LIST_USERS_REQUEST"
export const GET_LIST_USERS_SUCCESS = "GET_LIST_USERS_SUCCESS"
export const GET_LIST_USERS_ERROR = "GET_LIST_USERS_ERROR"
