export const GET_ME_REQUEST = "GET_ME_REQUEST";
export const GET_ME_SUCCESS = "GET_ME_SUCCESS";
export const GET_ME_ERROR = "GET_ME_ERROR";
export const GET_ME_RESET = "GETME_RESET";

export const SIGN_OUT = "SIGN_OUT";

export const CHANGEAVATAR_REQUEST = "CHANGEAVATAR_REQUEST";
export const CHANGEAVATAR_SUCCESS = "CHANGEAVATAR_SUCCESS";
export const CHANGEAVATAR_ERROR = "CHANGEAVATAR_ERROR";

export const CHANGEUSERNAME_REQUEST = "CHANGEUSERNAME_REQUEST";
export const CHANGEUSERNAME_SUCCESS = "CHANGEUSERNAME_SUCCESS";
export const CHANGEUSERNAME_ERROR = "CHANGEUSERNAME_ERROR";

export const SETQUESTION_REQUEST = "SETQUESTION_REQUEST";
export const SETQUESTION_SUCCESS = "SETQUESTION_SUCCESS";
export const SETQUESTION_ERROR = "SETQUESTION_ERROR";

// Them ban vao mang ban be sau khi accept yeu cau ket ban
export const ADD_FRIEND_TO_ARRAY="ADD_FRIEND_TO_ARRAY"
