export const INCREASE_SECONDS = "INCREASE_SECONDS";
export const GET_TIMES_ONLINE_REQUEST = "GET_TIMES_ONLINE_REQUEST"
export const GET_TIMES_ONLINE_SUCCESS = "GET_TIMES_ONLINE_SUCCESS"
export const GET_TIMES_ONLINE_ERROR = "GET_TIMES_ONLINE_ERROR"