export const GET_ALL_VIDEO_REQUEST = "GET_ALL_VIDEO_REQUEST";
export const GET_ALL_VIDEO_SUCCESS = "GET_ALL_VIDEO_SUCCESS";
export const GET_ALL_VIDEO_ERROR = "GET_ALL_VIDEO_ERROR";

export const GET_VIDEO_DETAILS_REQUEST = "GET_VIDEO_DETAILS_REQUEST";
export const GET_VIDEO_DETAILS_SUCCESS = "GET_VIDEO_DETAILS_SUCCESS";
export const GET_VIDEO_DETAILS_ERROR = "GET_VIDEO_DETAILS_ERROR";

// export const GET_COMMENTS_SUCCESS = "GET_COMMENTS_SUCCESS"
// export const GET_COMMENTS_REQUEST = "GET_COMMENTS_REQUEST"
// export const GET_COMMENTS_ERROR = "GET_COMMENTS_ERROR"

// export const POST_COMMENT_SUCCESS = "POST_COMMENT_SUCCESS"
// export const POST_COMMENT_REQUEST = "POST_COMMENT_REQUEST"
// export const POST_COMMENT_ERROR = "POST_COMMENT_ERROR"
